services:
  mt5-server:
    build:
      context: ./images/mt5-headless
      dockerfile: Dockerfile
    container_name: mt5_headless_container

    cap_add:
      - SYS_PTRACE
    security_opt:
      - seccomp:unconfined

    environment:
      - RESET_WINEPREFIX=${RESET_WINEPREFIX:-0}
      - INSTALL_MT5=${INSTALL_MT5:-0}
      - RUN_MT5=${RUN_MT5:-1}
      - BOOTSTRAP_TIMEOUT_SECONDS=${BOOTSTRAP_TIMEOUT_SECONDS:-420}
      - WINEDEBUG=${WINEDEBUG:--all}
      - MT5_LOGIN=${MT5_LOGIN}
      - MT5_PASSWORD=${MT5_PASSWORD}
      - MT5_SERVER=${MT5_SERVER}
      - ENABLE_VNC=${ENABLE_VNC:-1}
      - VNC_PORT=${VNC_PORT:-5900}
      - VNC_PASSWORD=${VNC_PASSWORD:?VNC_PASSWORD must be set}
    volumes:
      - mt5_persistent_data:/config/.wine
    ports:
      - "127.0.0.1:5901:5900"
      - "127.0.0.1:5555:5555"
    stop_grace_period: 30s
    restart: "no"

volumes:
  mt5_persistent_data: